// eslint.config.mjs

import js from "@eslint/js";
import tseslint from "typescript-eslint";
import playwright from "eslint-plugin-playwright";

export default tseslint.config(
  /*
   * These folders are generated by Playwright, Allure, npm, or builds.
   * They should not be linted.
   */
  {
    ignores: [
      "node_modules/**",
      "test-results/**",
      "playwright-report/**",
      "blob-report/**",
      "allure-results/**",
      "allure-report/**",
      "coverage/**",
      "dist/**",
      "build/**",
    ],
  },

  /*
   * Apply JavaScript and type-aware TypeScript recommendations
   * to all TypeScript files in the framework.
   */
  {
    files: ["**/*.ts"],

    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommendedTypeChecked,
    ],

    languageOptions: {
      parserOptions: {
        /*
         * Automatically finds the nearest tsconfig.json and provides
         * TypeScript type information to ESLint.
         *
         * This is required for no-floating-promises.
         */
        projectService: true,

        /*
         * Ensures paths are resolved relative to this config file,
         * regardless of where ESLint is executed from.
         */
        tsconfigRootDir: import.meta.dirname,
      },
    },

    rules: {
      /*
       * Most important rule for your exact problem.
       *
       * Detects:
       * validateHeader(...);
       * getMenuLinks();
       * someAsyncHelper();
       *
       * when the returned Promise is not awaited or otherwise handled.
       */
      "@typescript-eslint/no-floating-promises": "error",

      /*
       * Detects a Promise incorrectly used in places expecting
       * synchronous boolean/void values.
       */
      "@typescript-eslint/no-misused-promises": "error",

      /*
       * Prevent async functions without explicit return handling.
       * This is optional but useful for reusable framework helpers.
       */
      "@typescript-eslint/require-await": "warn",
    },
  },

  /*
   * Apply Playwright-specific rules to test and Playwright helper files.
   */
  {
    files: [
      "tests/**/*.ts",
      "src/fixtures/**/*.ts",
      "playwright.config.ts",
    ],

    extends: [playwright.configs["flat/recommended"]],

    rules: {
      /*
       * Detects unawaited Playwright APIs, including:
       *
       * test.step(...)
       * expect(locator).toBeVisible()
       * page.waitForResponse(...)
       * page.waitForRequest(...)
       */
      "playwright/missing-playwright-await": "error",

      /*
       * Detects unnecessary await usage for synchronous Playwright APIs.
       */
      "playwright/no-useless-await": "warn",

      /*
       * Prevent accidentally committed focused tests.
       */
      "playwright/no-focused-test": "error",

      /*
       * Detect expect statements outside Playwright tests/hooks.
       */
      "playwright/no-standalone-expect": "error",

      /*
       * Encourage locators instead of ElementHandle APIs.
       */
      "playwright/no-element-handle": "warn",

      /*
       * Discourage hard waits, which are a common source of flaky tests.
       */
      "playwright/no-wait-for-timeout": "warn",
    },
  },
);