version: '3.8'

services:
  jenkins:
    build: .   # Tells Docker Compose to build your custom Dockerfile
    container_name: jenkins-server
    user: root
    restart: unless-stopped
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - playwright_browsers:/var/playwright-browsers
    environment:
      - TZ=UTC

volumes:
  jenkins_data:
  playwright_browsers:
